   // With HYPRE
   $BS_Hypre = true   

   MODULE FV_DomainAndFields
      verbose_level = 0
      nb_space_dimensions = 2

      // Domain coordinates
      $DS_Xmin = 0.
      $DS_Xmax = 1.
      $DS_Ymin = 0.
      $DS_Ymax = 1.
      
      MODULE FV_Mesh
         $IS_NB_MESHES_X = 100
         $IS_NB_MESHES_Y = 100     	    
         vertices_coordinate_0 = regular_vector( $DS_Xmin, $IS_NB_MESHES_X, $DS_Xmax )
	 vertices_coordinate_1 = regular_vector( $DS_Ymin, $IS_NB_MESHES_Y, $DS_Ymax )
      END MODULE FV_Mesh 

      MODULE macro_colors
	 walls = < "left" "right" "bottom" "top" "bottom_left" "bottom_right" "top_left" "top_right" >	 
      END MODULE macro_colors
      
      MODULE splitting_strategy
         $IS_ndomX = 2
         $IS_ndomY = 2 
	 domain_decomposition = vector( $IS_ndomX, $IS_ndomY )
	 security_bandwidth = 1
      END MODULE splitting_strategy           

      MODULE interior_fields 

         MODULE temperature
            name = "temperature"
            nb_components = 1
            discretization = "centered"
            storage_depth = 1
	    MODULE DOFs_values
	      value = < 0. >
            END MODULE DOFs_values 
	    MODULE DOFs_imposed_value
               MODULE xxx
		  color = "walls"
                  component = 0
		  value = < 0. >
               END MODULE xxx       
            END MODULE DOFs_imposed_value
         END MODULE temperature 
	 
         MODULE temperature_staggered
            name = "temperature_staggered"
            nb_components = 2
            discretization = "staggered"
            storage_depth = 1
	    MODULE DOFs_values
	      value = < 0. 0. >
            END MODULE DOFs_values 
	    MODULE DOFs_imposed_value
               MODULE xxx
		  color = "walls"
                  component = 2
		  value = < 0. 0. >
               END MODULE xxx
            END MODULE DOFs_imposed_value
         END MODULE temperature_staggered 

         MODULE temperature_vertex
            name = "temperature_vertex"
            nb_components = 1
            discretization = "vertex"
            storage_depth = 1
	    MODULE DOFs_values
	      value = < 0. >
            END MODULE DOFs_values 
	    MODULE DOFs_imposed_value
               MODULE xxx
		  color = "walls"
                  component = 0
		  value = < 0. >
               END MODULE xxx       
            END MODULE DOFs_imposed_value
         END MODULE temperature_vertex 
	  	 
      END MODULE interior_fields

      MODULE FV_ResultSaver
         writing_mode = "binary"
	 MODULE temperature
            where_to_save = "at_vertices"
            entry_name = "Temperature"
            field = "temperature"
         END MODULE temperature
	 
	 MODULE temperature_staggered
            where_to_save = "at_vertices"
            entry_name = "Temperature_staggered"
            field = "temperature_staggered"
         END MODULE temperature_staggered
	 
	 MODULE temperature_vertex
            where_to_save = "at_vertices"
            entry_name = "Temperature_vertex"
            field = "temperature_vertex"
         END MODULE temperature_vertex 
      END MODULE FV_ResultSaver	 	 
   END MODULE FV_DomainAndFields


   MODULE FV_OneStepIteration
      concrete_name = "REG_HeatEquation"
      
      // Dimensionless parameter
      Peclet = 1.e0
      
      // Body term is 3.pi^2.sin(pi.x).sin(pi.y).sin(pi.z)
      BodyTerm = true
      
      MODULE REG_HeatEquationSystem_centered

               //**************************************************
               // Temperature unsteady matrix
               //
               MODULE MAT_A_TemperatureUnsteady_centered
                  concrete_name = "PETSc_MPIAIJ"
                  d_nz = 1
                  o_nz = 0
               END MODULE MAT_A_TemperatureUnsteady_centered

               //**************************************************
               // Temperature laplacian matrix
               //
               MODULE MAT_D_TemperatureDiffusion_centered
                  concrete_name = "PETSc_MPIAIJ"
                  d_nz = 7
                  o_nz = 3
               END MODULE MAT_D_TemperatureDiffusion_centered
               
               //**************************************************
               // Temperature solver
               //	       
	       MODULE SOLVER_Temperature_centered
                  concrete_name = "EXT_PETScSolver"
                  verbose = false
                  MODULE PETSc_Krylov_subspace_method
                     type = "cg"
                     verbose = false
                     ksp_max_it = 10000
                     ksp_rtol = 1.E-10
                     ksp_atol = 1.E-50
                  END MODULE PETSc_Krylov_subspace_method
                  // With Hypre
                  if ($BS_Hypre)
                  MODULE PETSc_preconditioner
                     type = "hypre"
                     MODULE options
                        pc_hypre_type = "boomeramg"
                     END MODULE options
                  END MODULE PETSc_preconditioner
                  // Without Hypre
                  if (!$BS_Hypre)
                  MODULE PETSc_preconditioner
                     type = "jacobi"
                  END MODULE PETSc_preconditioner
               END MODULE SOLVER_Temperature_centered

      END MODULE REG_HeatEquationSystem_centered
       
       
      MODULE REG_HeatEquationSystem_staggered

               //**************************************************
               // Temperature unsteady matrix
               //
               MODULE MAT_A_TemperatureUnsteady_staggered
                  concrete_name = "PETSc_MPIAIJ"
                  d_nz = 1
                  o_nz = 0
               END MODULE MAT_A_TemperatureUnsteady_staggered

               //**************************************************
               // Temperature laplacian matrix
               //
               MODULE MAT_D_TemperatureDiffusion_staggered
                  concrete_name = "PETSc_MPIAIJ"
                  d_nz = 7
                  o_nz = 3
               END MODULE MAT_D_TemperatureDiffusion_staggered
               
               //**************************************************
               // Temperature solver
               //	       
	       MODULE SOLVER_Temperature_staggered
                  concrete_name = "EXT_PETScSolver"
                  verbose = false
                  MODULE PETSc_Krylov_subspace_method
                     type = "cg"
                     verbose = false
                     ksp_max_it = 10000
                     ksp_rtol = 1.E-10
                     ksp_atol = 1.E-50
                  END MODULE PETSc_Krylov_subspace_method
                  // With Hypre
                  if ($BS_Hypre)
                  MODULE PETSc_preconditioner
                     type = "hypre"
                     MODULE options
                        pc_hypre_type = "boomeramg"
                     END MODULE options
                  END MODULE PETSc_preconditioner
                  // Without Hypre
                  if (!$BS_Hypre)
                  MODULE PETSc_preconditioner
                     type = "jacobi"
                  END MODULE PETSc_preconditioner
               END MODULE SOLVER_Temperature_staggered

      END MODULE REG_HeatEquationSystem_staggered


      MODULE REG_HeatEquationSystem_vertex

               //**************************************************
               // Temperature unsteady matrix
               //
               MODULE MAT_A_TemperatureUnsteady_vertex
                  concrete_name = "PETSc_MPIAIJ"
                  d_nz = 1
                  o_nz = 0
               END MODULE MAT_A_TemperatureUnsteady_vertex

               //**************************************************
               // Temperature laplacian matrix
               //
               MODULE MAT_D_TemperatureDiffusion_vertex
                  concrete_name = "PETSc_MPIAIJ"
                  d_nz = 7
                  o_nz = 3
               END MODULE MAT_D_TemperatureDiffusion_vertex
               
               //**************************************************
               // Temperature solver
               //	       
	       MODULE SOLVER_Temperature_vertex
                  concrete_name = "EXT_PETScSolver"
                  verbose = false
                  MODULE PETSc_Krylov_subspace_method
                     type = "cg"
                     verbose = false
                     ksp_max_it = 10000
                     ksp_rtol = 1.E-10
                     ksp_atol = 1.E-50
                  END MODULE PETSc_Krylov_subspace_method
                  // With Hypre
                  if ($BS_Hypre)
                  MODULE PETSc_preconditioner
                     type = "hypre"
                     MODULE options
                        pc_hypre_type = "boomeramg"
                     END MODULE options
                  END MODULE PETSc_preconditioner
                  // Without Hypre
                  if (!$BS_Hypre)
                  MODULE PETSc_preconditioner
                     type = "jacobi"
                  END MODULE PETSc_preconditioner
               END MODULE SOLVER_Temperature_vertex

      END MODULE REG_HeatEquationSystem_vertex 
             
   END MODULE FV_OneStepIteration
