MODULE MAC_Application

   // Application type   
   concrete_name = "MAC_ApplicationRestorer"

   MODULE MAC_ObjectReader
      restart_table_file_directory = join( getcwd(), "Savings" )
   END MODULE MAC_ObjectReader

   MODULE MAC_Application
   
      MODULE FV_TimeIterator
	 time_interval = 1.
         time_step = 1.E-2
      END MODULE FV_TimeIterator

      // Output & Backup copy
      $IS_ouput_backup_number = 1
   
      number_graphics_output_times = $IS_ouput_backup_number 
      number_state_saving_times = $IS_ouput_backup_number
      
      MODULE MAC_ObjectWriter
         type = "last_two_cycles"
         files_basename = join( getcwd(), "Savings", "saving.mac" )
         output_format = "text"
         force_write_at_last_time = true
      END MODULE MAC_ObjectWriter
      
   END MODULE MAC_Application
   
END MODULE MAC_Application
