MODULE MAC_Application

   // Application type
   concrete_name = "FV_StepByStepProgression"
   
   // Initial and final times
   $DS_time_initial = 0. 
   $DS_time_end = 1.e0
   
   MODULE FV_TimeIterator
      time_initial = $DS_time_initial
      time_end = $DS_time_end
      time_step = 1.E-2
   END MODULE FV_TimeIterator
   
   // Output & Backup copy
   $IS_ouput_backup_number = 1
   INITIAL_CYCLE_NUMBER = 1
   
   graphics_output_times = regular_vector( $DS_time_initial, $IS_ouput_backup_number, $DS_time_end ) 
   state_saving_times = regular_vector( $DS_time_initial, $IS_ouput_backup_number, $DS_time_end ) 
   
   MODULE MAC_ObjectWriter
      type = "last_two_cycles"
      files_basename = join( getcwd(), "Savings", "saving.mac" )
      output_format = "text"
      force_write_at_last_time = true      
   END MODULE MAC_ObjectWriter        
   
   #include ( join ( getcwd(), "InputFiles", "prob_def.mac" ) )   
      
END MODULE MAC_Application
