# Serial compiler and low level librairies
export BASILISK_SERCOMPIL_ENV=${PACIFIC_SERCOMPIL_ENV}
export BASILISK_SERCOMPIL_VERSION=${PACIFIC_SERCOMPIL_VERSION}
export BASILISK_C=${PACIFIC_SERCOMPIL_C}
export BASILISK_MESA_INCDIR=${PACIFIC_MESA_INCDIR}
export BASILISK_MESA_LIBDIR=${PACIFIC_MESA_LIBDIR}
export BASILISK_GLU_INCDIR=${PACIFIC_GLU_INCDIR}
export BASILISK_GLU_LIBDIR=${PACIFIC_GLU_LIBDIR}
if [[ "${PACIFIC_MESA_GLU_RECOM}" == "1" ]] 
then
  export LD_LIBRARY_PATH="${BASILISK_MESA_LIBDIR}:${LD_LIBRARY_PATH}"
  export LD_LIBRARY_PATH="${BASILISK_GLU_LIBDIR}:${LD_LIBRARY_PATH}"     
fi
export BASILISK_BITS_DEFAULT=${PACIFIC_BITS_DEFAULT}


# Basilisk variables
export OCTREE_HOME=${PACIFIC_HOME}/Octree
export BASILISK_HEAD=${OCTREE_HOME}/basilisk
export BASILISK_COMPILED=${OCTREE_HOME}/basilisk-${BASILISK_BITS_DEFAULT}-${BASILISK_SERCOMPIL_ENV}-${BASILISK_SERCOMPIL_VERSION}
export BASILISK=${BASILISK_COMPILED}/src
export BASILISK_DLMFD=${OCTREE_HOME}/DLMFD
export PATH="${BASILISK}:${PATH}"


# MPI
export BASILISK_MPI_ROOT=${PACIFIC_MPI_ROOT}
export BASILISK_MPI_DISTRIB=${PACIFIC_MPI_DISTRIB}
export BASILISK_MPI_VERSION=${PACIFIC_MPI_VERSION}
export BASILISK_MPI_INCDIR=${PACIFIC_MPI_INCDIR}
export BASILISK_MPI_GFORTRAN_INCDIR=${PACIFIC_MPI_GFORTRAN_INCDIR}
export BASILISK_MPI_BINDIR=${PACIFIC_MPI_BINDIR}
export BASILISK_MPI_LIBDIR=${PACIFIC_MPI_LIBDIR}
export BASILISK_MPI_C=${PACIFIC_MPI_C}


# Display
echo -e '\033[95m*** Octree Basilisk shell variables\033[0m'
echo -e '\033[95mOCTREE_HOME\033[0m =' $OCTREE_HOME
echo -e '\033[95mBASILISK_HEAD\033[0m =' $BASILISK_HEAD
echo -e '\033[95mBASILISK_COMPILED\033[0m =' $BASILISK_COMPILED
echo -e '\033[95mBASILISK\033[0m =' $BASILISK
echo -e '\033[95mBASILISK_BITS_DEFAULT\033[0m =' $BASILISK_BITS_DEFAULT
echo -e '\033[95mBASILISK_SERCOMPIL_ENV\033[0m =' $BASILISK_SERCOMPIL_ENV
echo -e '\033[95mBASILISK_SERCOMPIL_VERSION\033[0m =' $BASILISK_SERCOMPIL_VERSION
echo -e '\033[95mBASILISK_C\033[0m =' $BASILISK_C
echo -e '\033[95mBASILISK_MPI_ROOT\033[0m =' $BASILISK_MPI_ROOT
echo -e '\033[95mBASILISK_MPI_DISTRIB\033[0m =' $BASILISK_MPI_DISTRIB
echo -e '\033[95mBASILISK_MPI_VERSION\033[0m =' $BASILISK_MPI_VERSION
echo -e '\033[95mBASILISK_MPI_INCDIR\033[0m =' $BASILISK_MPI_INCDIR
echo -e '\033[95mBASILISK_MPI_GFORTRAN_INCDIR\033[0m =' $BASILISK_MPI_GFORTRAN_INCDIR
echo -e '\033[95mBASILISK_MPI_BINDIR\033[0m =' $BASILISK_MPI_BINDIR
echo -e '\033[95mBASILISK_MPI_LIBDIR\033[0m =' $BASILISK_MPI_LIBDIR
echo -e '\033[95mBASILISK_MPI_C\033[0m =' $BASILISK_MPI_C
echo -e '\033[95mBASILISK_MESA_INCDIR\033[0m =' $BASILISK_MESA_INCDIR
echo -e '\033[95mBASILISK_MESA_LIBDIR\033[0m =' $BASILISK_MESA_LIBDIR
echo -e '\033[95mBASILISK_GLU_INCDIR\033[0m =' $BASILISK_GLU_INCDIR
echo -e '\033[95mBASILISK_GLU_LIBDIR\033[0m =' $BASILISK_GLU_LIBDIR
echo -e '\033[95mBASILISK_DLMFD\033[0m =' $BASILISK_DLMFD
