# Definition
# Grains
export GRAINS_HOME=${PACIFIC_HOME}/GRAINS_V1
export GRAINS_BITS_DEFAULT=${PACIFIC_BITS_DEFAULT}
export GRAINS_SERCOMPIL_ENV=${PACIFIC_SERCOMPIL_ENV}
export GRAINS_SERCOMPIL_VERSION=${PACIFIC_SERCOMPIL_VERSION}
export GRAINS_MPICCC=${PACIFIC_MPI_CXX}
export GRAINS_CPP=${PACIFIC_SERCOMPIL_CPP}
export GRAINS_C=${PACIFIC_SERCOMPIL_C}
export GRAINS_COMPIL_OPT=${PACIFIC_OPT_FLAGS}
export GRAINS_Z_INCDIR=${PACIFIC_Z_INCDIR}
export GRAINS_Z_LIBDIR=${PACIFIC_Z_LIBDIR}

# Grains MPI
export GRAINS_MPI_ROOT=${PACIFIC_MPI_ROOT}
export GRAINS_MPI_DISTRIB=${PACIFIC_MPI_DISTRIB}
export GRAINS_MPI_VERSION=${PACIFIC_MPI_VERSION}
export GRAINS_MPI_INCDIR=${PACIFIC_MPI_INCDIR}
export GRAINS_MPI_BINDIR=${PACIFIC_MPI_BINDIR}
export GRAINS_MPI_LIBDIR=${PACIFIC_MPI_LIBDIR}
export GRAINS_MPI_LIBS="${PACIFIC_MPI_CPPLIBS}"
# End definition


# Other environment variables
source $GRAINS_HOME/Env/grains_default.env.sh
