CFLAGS += -O2 -events
include $(BASILISK)/Makefile.defs
CFLAGS += -I${BASILISK_MESA_GLU_INSTALL} -L${BASILISK_MESA_GLU_INSTALL}/lib -I${OCTREE_HOME} -I${OCTREE_HOME}/basilisk/src/grid

test-acceleration-2.tst:
test-acceleration-2.c: test-acceleration.c
	ln -s test-acceleration.c test-acceleration-2.c

test-acceleration-3.tst:
test-acceleration-3.c: test-acceleration.c
	ln -s test-acceleration.c test-acceleration-3.c

reversed-shear-2.tst:
reversed-shear-2.c: reversed-shear.c
	ln -s reversed-shear.c reversed-shear-2.c

reversed-shear-3.tst:
reversed-shear-3.c: reversed-shear.c
	ln -s reversed-shear.c reversed-shear-3.c

reversed-shear-4.tst:
reversed-shear-4.c: reversed-shear.c
	ln -s reversed-shear.c reversed-shear-4.c

reversed-shear-5.tst:
reversed-shear-5.c: reversed-shear.c
	ln -s reversed-shear.c reversed-shear-5.c

reversed-shear-6.tst:
reversed-shear-6.c: reversed-shear.c
	ln -s reversed-shear.c reversed-shear-6.c

reversed-shear-7.tst:
reversed-shear-7.c: reversed-shear.c
	ln -s reversed-shear.c reversed-shear-7.c

reversed-shear-8.tst:
reversed-shear-8.c: reversed-shear.c
	ln -s reversed-shear.c reversed-shear-8.c

compute_J.tst: CFLAGS += -DCOMPUTE_J=1
compute_J.c: nd-shear-relax-debug.c
	ln -s nd-shear-relax-debug.c compute_J.c

compute_J2.tst: CFLAGS += -DCOMPUTE_J=1
compute_J2.c: nd-shear-relax-debug.c
	ln -s nd-shear-relax-debug.c compute_J2.c

compute_J3.tst: CFLAGS += -DCOMPUTE_J=1
compute_J3.c: nd-shear-relax-debug.c
	ln -s nd-shear-relax-debug.c compute_J3.c

project_G_stress_only.tst:
project_G_stress_only.c: nd-shear-relax-debug.c
	ln -s nd-shear-relax-debug.c project_G_stress_only.c

neo-hookean-shear-1.tst:
neo-hookean-shear-1.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-1.c

neo-hookean-shear-2.tst:
neo-hookean-shear-2.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-2.c

neo-hookean-shear-3.tst:
neo-hookean-shear-3.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-3.c

neo-hookean-shear-4.tst:
neo-hookean-shear-4.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-4.c

neo-hookean-shear-5.tst:
neo-hookean-shear-5.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-5.c

neo-hookean-shear-6.tst:
neo-hookean-shear-6.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-6.c

neo-hookean-shear-7.tst:
neo-hookean-shear-7.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-7.c

neo-hookean-shear-9.tst:
neo-hookean-shear-9.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-9.c

neo-hookean-shear-10.tst:
neo-hookean-shear-10.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-10.c

neo-hookean-shear-11.tst:
neo-hookean-shear-11.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-11.c

neo-hookean-shear-12.tst:
neo-hookean-shear-12.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-12.c

neo-hookean-shear-13.tst:
neo-hookean-shear-13.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-13.c

neo-hookean-shear-14.tst:
neo-hookean-shear-14.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-14.c

neo-hookean-shear-15.tst:
neo-hookean-shear-15.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-15.c

neo-hookean-shear-16.tst:
neo-hookean-shear-16.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-16.c

neo-hookean-shear-17.tst:
neo-hookean-shear-17.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-17.c

neo-hookean-shear-18.tst:
neo-hookean-shear-18.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-18.c

neo-hookean-shear-19.tst:
neo-hookean-shear-19.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-19.c

neo-hookean-shear-20.tst:
neo-hookean-shear-20.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-20.c

neo-hookean-shear-21.tst:
neo-hookean-shear-21.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-21.c

neo-hookean-shear-22.tst:
neo-hookean-shear-22.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-22.c

neo-hookean-shear-23.tst:
neo-hookean-shear-23.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-23.c

neo-hookean-shear-24.tst:
neo-hookean-shear-24.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-24.c

neo-hookean-shear-25.tst:
neo-hookean-shear-25.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-25.c

neo-hookean-shear-26.tst:
neo-hookean-shear-26.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-26.c

neo-hookean-shear-27.tst:
neo-hookean-shear-27.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-27.c

neo-hookean-shear-28.tst:
neo-hookean-shear-28.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-28.c

neo-hookean-shear-29.tst:
neo-hookean-shear-29.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-29.c

#G=t*t, normal_extension, J extended along normals, lvl 6, rest_dt=0.05, no CSF
neo-hookean-shear-30.tst:
neo-hookean-shear-30.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-30.c

#G=t*t, normal_extension, J extended along normals, lvl 6, rest_dt=0.05, CSF in acceleration event
neo-hookean-shear-31.tst:
neo-hookean-shear-31.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-31.c

#G=t*t, normal_extension, J extended along normals, lvl 6, rest_dt=0.05, CSF in acceleration event, Ca=0.0025
neo-hookean-shear-32.tst:
neo-hookean-shear-32.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-32.c

#G=t*t, normal_extension, J extended along normals, lvl 7, rest_dt=0.05, CSF in acceleration event, Ca back to 0.025
neo-hookean-shear-33.tst:
neo-hookean-shear-33.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-33.c

#G=t*t, normal_extension, J extended along normals, lvl 6, rest_dt=0.05, CSF in acceleration event, Ca=0.025, no mb extra layer
neo-hookean-shear-34.tst:
neo-hookean-shear-34.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-34.c

#G is advected, PROJECT_G=0, normal_extension, J extended along normals, lvl 6, rest_dt=0.05, CSF in acceleration event, Ca=0.025, no mb extra layer
neo-hookean-shear-35.tst:
neo-hookean-shear-35.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-35.c

#G is advected, PROJECT_G=0, normal_extension, J extended along normals, lvl 6, rest_dt=0.05, CSF in acceleration event, Ca=0.025, no mb extra layer
neo-hookean-shear-36.tst:
neo-hookean-shear-36.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-36.c

#narrower smearing of caps[], G=t*t, normal_extension, J extended along normals, lvl 6, rest_dt=0.05, CSF in acceleration event, Ca=0.025, no mb extra layer
neo-hookean-shear-37.tst:
neo-hookean-shear-37.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-37.c

#narrower smearing of caps[], G=t*t, normal_extension, J extended along normals, lvl 6, rest_dt=0.05, CSF in acceleration event, Ca=0.025, 1 cell in mb extra layer
neo-hookean-shear-38.tst:
neo-hookean-shear-38.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-38.c

#narrower smearing of caps[], G=t*t, normal_extension, J extended along normals, lvl 6, rest_dt=0.05, CSF in acceleration event, Ca=0.025, 2 cells in mb extra layer
neo-hookean-shear-39.tst:
neo-hookean-shear-39.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-39.c

#same as neo-hookean-shear-34, just reproducing it
neo-hookean-shear-40.tst:
neo-hookean-shear-40.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-40.c

#same as neo-hookean-shear-40, but extension of normals from height functions (bug introduced sometime after neo-hookean-shear-34)
neo-hookean-shear-41.tst:
neo-hookean-shear-41.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-41.c

#same as neo-hookean-shear-41, but rest_dt=0.5 instead of 0.05 and NB_MB_EXTRA_LAYERS=0
neo-hookean-shear-42.tst:
neo-hookean-shear-42.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-42.c

#same as neo-hookean-shear-41, but rest_dt=0.5 instead of 0.05 (NB_MB_EXTRA_LAYERS=2)
neo-hookean-shear-43.tst:
neo-hookean-shear-43.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-43.c

#same as neo-hookean-shear-43, but NORMAL_EXTENSION=1
neo-hookean-shear-44.tst:
neo-hookean-shear-44.c: neo-hookean-shear.c
	ln -s neo-hookean-shear.c neo-hookean-shear-44.c

#no normal_vector_extension(extended_n) in elasticity_2D.h
nhs2d-2.tst:
nhs2d-2.c: nhs2d.c
	ln -s nhs2d.c nhs2d-2.c

plug_flow_fail.tst:
plug_flow_fail.c: plug_flow.c
	ln -s plug_flow.c plug_flow_fail.c

sinusoidal-shear-uy-free.tst: CFLAGS += -DIMPOSE_UY=0
sinusoidal-shear-uy-free.c: sinusoidal-shear.c
	ln -s sinusoidal-shear.c sinusoidal-shear-uy-free.c

sinusoidal-shear-uy-imposed.tst: CFLAGS += -DIMPOSE_UY=1 -DGRAD_UF=0
sinusoidal-shear-uy-imposed.c: sinusoidal-shear.c
	ln -s sinusoidal-shear.c sinusoidal-shear-uy-imposed.c

sinusoidal-shear-uy-free-grad-uf.tst: CFLAGS += -DIMPOSE_UY=0 -DGRAD_UF=1
sinusoidal-shear-uy-free-grad-uf.c: sinusoidal-shear.c
	ln -s sinusoidal-shear.c sinusoidal-shear-uy-free-grad-uf.c

sinusoidal-shear-uy-imposed-grad-uf.tst: CFLAGS += -DIMPOSE_UY=1 -DGRAD_UF=1
sinusoidal-shear-uy-imposed-grad-uf.c: sinusoidal-shear.c
	ln -s sinusoidal-shear.c sinusoidal-shear-uy-imposed-grad-uf.c

sinusoidal-shear-uyandufy-free-grad-uf.tst: CFLAGS += -DIMPOSE_UY=0 -DGRAD_UF=1 -DIMPOSE_UY_AND_UFY=0
sinusoidal-shear-uyandufy-free-grad-uf.c: sinusoidal-shear.c
	ln -s sinusoidal-shear.c sinusoidal-shear-uyandufy-free-grad-uf.c

sinusoidal-shear-uyandufy-imposed-grad-uf.tst: CFLAGS += -DIMPOSE_UY=1 -DGRAD_UF=1 -DIMPOSE_UY_AND_UFY=1
sinusoidal-shear-uyandufy-imposed-grad-uf.c: sinusoidal-shear.c
	ln -s sinusoidal-shear.c sinusoidal-shear-uyandufy-imposed-grad-uf.c

sinusoidal-shear-uy-imposed-endtimestep.tst: CFLAGS += -DIMPOSE_UY=1 -DGRAD_UF=0
sinusoidal-shear-uy-imposed-endtimestep.c: sinusoidal-shear.c
	ln -s sinusoidal-shear.c sinusoidal-shear-uy-imposed-endtimestep.c

sinusoidal-shear-10-repeats.tst:
sinusoidal-shear-10-repeats.c: sinusoidal-shear.c
	ln -s sinusoidal-shear.c sinusoidal-shear-10-repeats.c

sinusoidal-shear-lvl6.tst:
sinusoidal-shear-lvl6.c: sinusoidal-shear.c
	ln -s sinusoidal-shear.c sinusoidal-shear-lvl6.c

sinusoidal-shear-lvl7.tst: CFLAGS += -DLEVEL=7
sinusoidal-shear-lvl7.c: sinusoidal-shear.c
	ln -s sinusoidal-shear.c sinusoidal-shear-lvl7.c

scalar_extension_2.tst:
scalar_extension_2.c: scalar_extension.c
	ln -s scalar_extension.c scalar_extension_2.c

scalar_extension_3.tst:
scalar_extension_3.c: scalar_extension.c
	ln -s scalar_extension.c scalar_extension_3.c

scalar_extension_4.tst:
scalar_extension_4.c: scalar_extension.c
	ln -s scalar_extension.c scalar_extension_4.c

scalar_extension_5.tst:
scalar_extension_5.c: scalar_extension.c
	ln -s scalar_extension.c scalar_extension_5.c

scalar_extension_6.tst:
scalar_extension_6.c: scalar_extension.c
	ln -s scalar_extension.c scalar_extension_6.c

scalar_extension_7.tst:
scalar_extension_7.c: scalar_extension.c
	ln -s scalar_extension.c scalar_extension_7.c

#For 2D_pozrikidis2000 to 2D_pozrikidis2000_13: no normal_vector_extension(extended_n) in elasticity_2D.h
2D_pozrikidis2000_2.tst:
2D_pozrikidis2000_2.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_2.c

2D_pozrikidis2000_3.tst: CFLAGS += -DLEVEL=7
2D_pozrikidis2000_3.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_3.c

2D_pozrikidis2000_4.tst:
2D_pozrikidis2000_4.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_4.c

2D_pozrikidis2000_5.tst: CFLAGS += -DSIZE=8
2D_pozrikidis2000_5.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_5.c

2D_pozrikidis2000_6.tst: CFLAGS += -DSIZE=8 -DLEVEL=7
2D_pozrikidis2000_6.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_6.c

2D_pozrikidis2000_7.tst: CFLAGS += -DSIZE=16 -DLEVEL=8 -DRESTRICT_DT=0.01
2D_pozrikidis2000_7.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_7.c

2D_pozrikidis2000_8.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DSTART_SHEAR=1
2D_pozrikidis2000_8.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_8.c

2D_pozrikidis2000_9.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125
2D_pozrikidis2000_9.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_9.c

2D_pozrikidis2000_10.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DSTART_SHEAR=1 -DCA=0.0125
2D_pozrikidis2000_10.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_10.c

2D_pozrikidis2000_11.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.04
2D_pozrikidis2000_11.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_11.c

2D_pozrikidis2000_12.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.125 -DTEND=30.
2D_pozrikidis2000_12.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_12.c

2D_pozrikidis2000_13.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.4 -DTEND=50.
2D_pozrikidis2000_13.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_13.c

2D_pozrikidis2000_14.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125
2D_pozrikidis2000_14.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_14.c

#(Likely) fixed the normal extension routine, which is used in the 15th test on
2D_pozrikidis2000_15.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125 -DNORMAL_EXTENSION=1
2D_pozrikidis2000_15.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_15.c

2D_pozrikidis2000_16.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.003125 -DNORMAL_EXTENSION=1
2D_pozrikidis2000_16.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_16.c

2D_pozrikidis2000_17.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.04 -DNORMAL_EXTENSION=1
2D_pozrikidis2000_17.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_17.c

#same as 2D_pozrikidis2000_14
2D_pozrikidis2000_18.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125
2D_pozrikidis2000_18.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_18.c

#same as 2D_pozrikidis2000_15 but started shear at t=0
2D_pozrikidis2000_19.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DSTART_SHEAR=1
2D_pozrikidis2000_19.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_19.c

#same as 2D_pozrikidis2000_14 but no mb extra layer
2D_pozrikidis2000_20.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_20.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_20.c

#same as 2D_pozrikidis2000_15 but no mb extra layer
2D_pozrikidis2000_21.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_21.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_21.c

#same as 2D_pozrikidis2000_21 but with MPI
2D_pozrikidis2000_mpi_21.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_mpi_21.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_mpi.c 2D_pozrikidis2000_mpi_21.c

#same as 2D_pozrikidis2000_21 but with adaptivity
2D_pozrikidis2000_adapt_2.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_adapt_2.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_adapt.c 2D_pozrikidis2000_adapt_2.c

#same as 2D_pozrikidis2000_21
2D_pozrikidis2000_22.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_22.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_22.c

#same as 2D_pozrikidis2000_adapt_2 but with 1.e-2 as a tolerance for adapting velocity
2D_pozrikidis2000_adapt_3.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_adapt_3.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_adapt.c 2D_pozrikidis2000_adapt_3.c

#same as 2D_pozrikidis2000_adapt_2 but with 1.e-3 as a tolerance for adapting velocity
2D_pozrikidis2000_adapt_4.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_adapt_4.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_adapt.c 2D_pozrikidis2000_adapt_4.c

#same as 2D_pozrikidis2000_22 (with perf.h included)
2D_pozrikidis2000_23.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_23.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_23.c

#same as 2D_pozrikidis2000_23 with maximum iteration of extension set to 20
2D_pozrikidis2000_24.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0 -DTRACE=2 -DMAX_ITER_EXTENSION=20
2D_pozrikidis2000_24.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_24.c

#same as 2D_pozrikidis2000_24 but with lvl 8 and TEND=6
2D_pozrikidis2000_25.tst: CFLAGS += -DSIZE=8 -DLEVEL=8 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0 -DTRACE=2 -DMAX_ITER_EXTENSION=20 -DTEND=6
2D_pozrikidis2000_25.c: 2D_pozrikidis2000.c
	ln -s 2D_pozrikidis2000.c 2D_pozrikidis2000_25.c

#same as 2D_pozrikidis2000_adapt_3 but with level 8 as max level
2D_pozrikidis2000_adapt_5.tst: CFLAGS += -DSIZE=8 -DLEVEL=8 -DU_TOL=1.e-2 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_adapt_5.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_adapt.c 2D_pozrikidis2000_adapt_5.c

#same as 2D_pozrikidis2000_adapt_3 but with level 9 as max level
2D_pozrikidis2000_adapt_6.tst: CFLAGS += -DSIZE=8 -DLEVEL=9 -DU_TOL=1.e-2 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_adapt_6.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_adapt.c 2D_pozrikidis2000_adapt_6.c

#same as 2D_pozrikidis2000_adapt_3 (with perf.h included)
2D_pozrikidis2000_adapt_7.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DU_TOL=1.e-2 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_adapt_7.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_adapt.c 2D_pozrikidis2000_adapt_7.c

#same as 2D_pozrikidis2000_adapt_3 but with 5.e-3 as a tolerance for adapting velocity
2D_pozrikidis2000_adapt_8.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DU_TOL=5.e-3 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0
2D_pozrikidis2000_adapt_8.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_adapt.c 2D_pozrikidis2000_adapt_8.c

#same as 2D_pozrikidis2000_adapt_7 but with maximum iterations in extension set to 20
2D_pozrikidis2000_adapt_9.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DU_TOL=1.e-2 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0 -DTRACE=2 -DMAX_ITER_EXTENSION=20
2D_pozrikidis2000_adapt_9.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_adapt.c 2D_pozrikidis2000_adapt_9.c

#same as 2D_pozrikidis2000_adapt_9 but with u_tol twice smaller (5.e-3)
2D_pozrikidis2000_adapt_10.tst: CFLAGS += -DSIZE=8 -DLEVEL=7 -DU_TOL=5.e-3 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0 -DTRACE=2 -DMAX_ITER_EXTENSION=20
2D_pozrikidis2000_adapt_10.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_adapt.c 2D_pozrikidis2000_adapt_10.c

#same as 2D_pozrikidis2000_adapt_10 but with lvl 8 and TEND=6
2D_pozrikidis2000_adapt_11.tst: CFLAGS += -DSIZE=8 -DLEVEL=8 -DU_TOL=5.e-3 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0 -DTRACE=2 -DMAX_ITER_EXTENSION=20 -DTEND=6
2D_pozrikidis2000_adapt_11.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_adapt.c 2D_pozrikidis2000_adapt_11.c

#same as 2D_pozrikidis2000_adapt_11 but with restrict_dt set to 0.025
2D_pozrikidis2000_adapt_12.tst: CFLAGS += -DSIZE=8 -DLEVEL=8 -DU_TOL=5.e-3 -DCA=0.0125 -DNORMAL_EXTENSION=1 -DNB_MB_EXTRA_LAYERS=0 -DTRACE=2 -DMAX_ITER_EXTENSION=20 -DTEND=6 -DRESTRICT_DT=0.005
2D_pozrikidis2000_adapt_12.c: 2D_pozrikidis2000_mpi.c
	ln -s 2D_pozrikidis2000_adapt.c 2D_pozrikidis2000_adapt_12.c

### --- Reproducing fig 11 of Ii 2012 in 2D --- ###
shear_bending_2D_0.tst: CFLAGS += -DND_EB=0.
shear_bending_2D_0.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_0.c

shear_bending_2D_1.tst: CFLAGS += -DND_EB=0.01
shear_bending_2D_1.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_1.c

shear_bending_2D_2.tst: CFLAGS += -DND_EB=0.025
shear_bending_2D_2.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_2.c

shear_bending_2D_3.tst: CFLAGS += -DND_EB=0.0375
shear_bending_2D_3.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_3.c

shear_bending_2D_4.tst: CFLAGS += -DND_EB=0. -DDT_MAX=1.e-5
shear_bending_2D_4.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_4.c

shear_bending_2D_5.tst: CFLAGS += -DND_EB=0.01 -DDT_MAX=1.e-5
shear_bending_2D_5.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_5.c

shear_bending_2D_6.tst: CFLAGS += -DND_EB=0.025 -DDT_MAX=1.e-5
shear_bending_2D_6.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_6.c

shear_bending_2D_7.tst: CFLAGS += -DND_EB=0.0375 -DDT_MAX=1.e-5
shear_bending_2D_7.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_7.c

shear_bending_2D_8.tst: CFLAGS += -DND_EB=0. -DT_END=10
shear_bending_2D_8.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_8.c

shear_bending_2D_9.tst: CFLAGS += -DND_EB=0.01 -DT_END=10
shear_bending_2D_9.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_9.c

shear_bending_2D_10.tst: CFLAGS += -DND_EB=0.025 -DT_END=10
shear_bending_2D_10.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_10.c

shear_bending_2D_11.tst: CFLAGS += -DND_EB=0.0375 -DT_END=10
shear_bending_2D_11.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_11.c

shear_bending_2D_12.tst: CFLAGS += -DND_EB=0. -DAMR=1
shear_bending_2D_12.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_12.c

shear_bending_2D_13.tst: CFLAGS += -DND_EB=0.01 -DAMR=1
shear_bending_2D_13.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_13.c

shear_bending_2D_14.tst: CFLAGS += -DND_EB=0.025 -DAMR=1
shear_bending_2D_14.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_14.c

shear_bending_2D_15.tst: CFLAGS += -DND_EB=0.0375 -DAMR=1
shear_bending_2D_15.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_15.c

shear_bending_2D_16.tst: CFLAGS += -DND_EB=0. -DAMR=1 -DT_END=10
shear_bending_2D_16.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_16.c

shear_bending_2D_17.tst: CFLAGS += -DND_EB=0.01 -DAMR=1 -DT_END=10
shear_bending_2D_17.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_17.c

shear_bending_2D_18.tst: CFLAGS += -DND_EB=0.025 -DAMR=1 -DT_END=10
shear_bending_2D_18.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_18.c

shear_bending_2D_19.tst: CFLAGS += -DND_EB=0.0375 -DAMR=1 -DT_END=10
shear_bending_2D_19.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_19.c

shear_bending_2D_20.tst: CFLAGS += -DND_EB=0.001 -DAMR=1 -DT_END=10
shear_bending_2D_20.c: shear_bending_2D.c
	ln -s shear_bending_2D.c shear_bending_2D_20.c

## 2D RBC in a parabolic flow
poiseuille_nh_rbc_2d_1.tst: CFLAGS += -DDT_MAX=0.0001
poiseuille_nh_rbc_2d_1.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_1.c

poiseuille_nh_rbc_2d_2.tst: CFLAGS += -DT_END=.5
poiseuille_nh_rbc_2d_2.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_2.c

# same as poiseuille_nh_rbc_2d but without bending resistance
poiseuille_nh_rbc_2d_3.tst: CFLAGS += -DND_EB=0
poiseuille_nh_rbc_2d_3.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_3.c

# same as poiseuille_nh_rbc_2d but without reference curvature
poiseuille_nh_rbc_2d_4.tst: CFLAGS += -DREF_CURV=0
poiseuille_nh_rbc_2d_4.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_4.c

#same as poiseuille_nh_rbc_2d but with extended bending quantities
poiseuille_nh_rbc_2d_5.tst:
poiseuille_nh_rbc_2d_5.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_5.c

# same as poiseuille_nh_rbc_2d_5 but without reference curvature
poiseuille_nh_rbc_2d_6.tst: CFLAGS += -DREF_CURV=0
poiseuille_nh_rbc_2d_6.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_6.c

# same as poiseuille_nh_rbc_2d_5 but with small time step
poiseuille_nh_rbc_2d_7.tst: CFLAGS += -DDT_MAX=0.0001
poiseuille_nh_rbc_2d_7.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_7.c

#same as poiseuille_nh_rbc_2d_5 but with properly extended bending quantities (including m_ref...)
poiseuille_nh_rbc_2d_8.tst:
poiseuille_nh_rbc_2d_8.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_8.c

#same as poiseuille_nh_rbc_2d_8
poiseuille_nh_rbc_2d_9.tst:
poiseuille_nh_rbc_2d_9.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_9.c

#same as poiseuille_nh_rbc_2d_9 but with larger time step
poiseuille_nh_rbc_2d_10.tst: CFLAGS += -DDT_MAX=0.001
poiseuille_nh_rbc_2d_10.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_10.c

#same as poiseuille_nh_rbc_2d_8 but including non-linear advection term (no Stokes) and using dimensional parameters
poiseuille_nh_rbc_2d_11.tst: CFLAGS += -DSTOKES_FLOW=true -DSIZE=0.00004 -DRADIUS=0.000004 -DMU=0.0012 -DU_MAX=0.001 -DG_SHEAR=6.e-6 -DE_BEND=1.8e-19 -DRHO=1025 -DDT_MAX=2.5e-7 -DT_END=0.1 -DTRASH=1 -DOUTPUT_FREQ=i++
poiseuille_nh_rbc_2d_11.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_11.c

#same as poiseuille_nh_rbc_2d_9 with properly defined level-set and new list scalar extension
poiseuille_nh_rbc_2d_12.tst: CFLAGS += -DMTRACE=1
poiseuille_nh_rbc_2d_12.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_12.c

#same as poiseuille_nh_rbc_2d_9 with properly defined level-set and new list scalar extension
poiseuille_nh_rbc_2d_mpi_12.tst: CFLAGS += -DMTRACE=1
poiseuille_nh_rbc_2d_mpi_12.c: poiseuille_nh_rbc_2d_mpi.c
	ln -s poiseuille_nh_rbc_2d_mpi.c poiseuille_nh_rbc_2d_mpi_12.c

#same as poiseuille_nh_rbc_2d_9 but less deformable RBC (but same bending resistance)
poiseuille_nh_rbc_2d_13.tst: CFLAGS += -DCA=0.02 -DDT_MAX=2.5e-5
poiseuille_nh_rbc_2d_13.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_13.c

#same as poiseuille_nh_rbc_2d_13 but in MPI
poiseuille_nh_rbc_2d_mpi_13.tst: CFLAGS += -DCA=0.02 -DDT_MAX=2.5e-5
poiseuille_nh_rbc_2d_mpi_13.c: poiseuille_nh_rbc_2d_mpi.c
	ln -s poiseuille_nh_rbc_2d_mpi.c poiseuille_nh_rbc_2d_mpi_13.c

#same as poiseuille_nh_rbc_2d_mpi_13 but without bending force
poiseuille_nh_rbc_2d_mpi_14.tst: CFLAGS += -DCA=0.02 -DDT_MAX=2.5e-5 -DND_EB=0
poiseuille_nh_rbc_2d_mpi_14.c: poiseuille_nh_rbc_2d_mpi.c
	ln -s poiseuille_nh_rbc_2d_mpi.c poiseuille_nh_rbc_2d_mpi_14.c

# same as poiseuille_nh_rbc_2d_3 but with properly defined level-set and new list scalar extension
poiseuille_nh_rbc_2d_15.tst: CFLAGS += -DND_EB=0 -DREF_CURV=0
poiseuille_nh_rbc_2d_15.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_15.c

#same as poiseuille_nh_rbc_2d_9 with properly defined level-set... But old scalar_extension.
poiseuille_nh_rbc_2d_16.tst: CFLAGS += -DMTRACE=1
poiseuille_nh_rbc_2d_16.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_16.c

#same as poiseuille_nh_rbc_2d_16 but with different views
poiseuille_nh_rbc_2d_17.tst: CFLAGS += -DMTRACE=1 -DOUTPUT_FREQ=i++ -DTEND=0.5
poiseuille_nh_rbc_2d_17.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_17.c

#same as poiseuille_nh_rbc_2d_17 but without bending force
poiseuille_nh_rbc_2d_18.tst: CFLAGS += -DMTRACE=1 -DOUTPUT_FREQ=i++ -DTEND=0.5 -DND_EB=0
poiseuille_nh_rbc_2d_18.c: poiseuille_nh_rbc_2d.c
	ln -s poiseuille_nh_rbc_2d.c poiseuille_nh_rbc_2d_18.c

debug_multiple_scalar_extension_1.tst: CFLAGS += -DOUTPUT_FREQ=t+=0.01 -DSINGLE_EXT=1 -DT_END=3. -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_1.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_1.c

debug_multiple_scalar_extension_2.tst: CFLAGS += -DOUTPUT_FREQ=t+=0.01 -DSINGLE_EXT=0 -DT_END=3. -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_2.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_2.c

debug_multiple_scalar_extension_3.tst: CFLAGS += -DOUTPUT_FREQ=t+=0.01 -DSINGLE_EXT=0 -DT_END=3. -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_3.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_3.c

debug_multiple_scalar_extension_4.tst: CFLAGS += -DOUTPUT_FREQ=t+=0.01 -DSINGLE_EXT=0 -DT_END=3. -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_4.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_4.c

# no initialization of q_prev=1 outside the membrane region
debug_multiple_scalar_extension_5.tst: CFLAGS += -DOUTPUT_FREQ=t+=0.01 -DSINGLE_EXT=0 -DT_END=3. -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_5.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_5.c

debug_multiple_scalar_extension_6.tst: CFLAGS += -DOUTPUT_FREQ=t+=0.01 -DSINGLE_EXT=1 -DT_END=3. -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_6.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_6.c

# no initialization of q_prev=1 outside the membrane region
debug_multiple_scalar_extension_7.tst: CFLAGS += -DOUTPUT_FREQ=t+=0.01 -DSINGLE_EXT=0 -DT_END=3. -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_7.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_7.c

# no initialization of q_prev=1 outside the membrane region and boundary q before
debug_multiple_scalar_extension_8.tst: CFLAGS += -DOUTPUT_FREQ=t+=0.01 -DSINGLE_EXT=0 -DT_END=3. -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_8.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_8.c

debug_multiple_scalar_extension_9.tst: CFLAGS += -DOUTPUT_FREQ=t+=0.01 -DSINGLE_EXT=0 -DT_END=3. -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_9.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_9.c

#no initialization of q_prev outside gamma
debug_multiple_scalar_extension_10.tst: CFLAGS += -DOUTPUT_FREQ=i++ -DSINGLE_EXT=1 -DEND_IT=3000 -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_10.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_10.c

#initialization of q_prev=1 outside gamma
debug_multiple_scalar_extension_11.tst: CFLAGS += -DOUTPUT_FREQ=i++ -DSINGLE_EXT=1 -DEND_IT=3000 -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_11.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_11.c

#no initialization of q_prev outside gamma
debug_multiple_scalar_extension_12.tst: CFLAGS += -DOUTPUT_FREQ=i++ -DSINGLE_EXT=0 -DEND_IT=3000 -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_12.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_12.c

#initialization of q_prev=1 outside gamma
debug_multiple_scalar_extension_13.tst: CFLAGS += -DOUTPUT_FREQ=i++ -DSINGLE_EXT=0 -DEND_IT=3000 -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_13.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_13.c

#no initialization of q_prev outside gamma, normals at t=0 initialized from grad caps
debug_multiple_scalar_extension_14.tst: CFLAGS += -DOUTPUT_FREQ=i++ -DSINGLE_EXT=0 -DEND_IT=3000 -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_14.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_14.c

#initialization of q_prev=1 outside gamma, normals at t=0 initialized from grad caps
debug_multiple_scalar_extension_15.tst: CFLAGS += -DOUTPUT_FREQ=i++ -DSINGLE_EXT=0 -DEND_IT=3000 -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_15.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_15.c

#no initialization of q_prev outside gamma, normals at t=0 initialized from grad caps, no bending
debug_multiple_scalar_extension_16.tst: CFLAGS += -DOUTPUT_FREQ=i++ -DSINGLE_EXT=0 -DEND_IT=3000 -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_16.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_16.c

#initialization of q_prev=1 outside gamma, normals at t=0 initialized from grad caps, no bending
debug_multiple_scalar_extension_17.tst: CFLAGS += -DOUTPUT_FREQ=i++ -DSINGLE_EXT=0 -DEND_IT=3000 -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_17.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_17.c

#no initialization of q_prev outside gamma, normals at t=0 initialized from grad caps, no bending
debug_multiple_scalar_extension_18.tst: CFLAGS += -DOUTPUT_FREQ=i++ -DSINGLE_EXT=0 -DEND_IT=30 -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_18.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_18.c

#no initialization of q_prev outside gamma, normals at t=0 initialized from grad caps, no bending
debug_multiple_scalar_extension_19.tst: CFLAGS += -DOUTPUT_FREQ=i++ -DSINGLE_EXT=0 -DEND_IT=3000 -DMAX_ITER_EXTENSION=10
debug_multiple_scalar_extension_19.c: debug_multiple_scalar_extension.c
	ln -s debug_multiple_scalar_extension.c debug_multiple_scalar_extension_19.c

membrane_region_3d.tst:
membrane_region_3d.c: membrane_region.c
	ln -s membrane_region.c membrane_region_3d.c

# Project the tensor G using analytical normals
constant_elongation_3d_2.tst:
constant_elongation_3d_2.c: constant_elongation_3d.c
	ln -s constant_elongation_3d.c constant_elongation_3d_2.c

# Project the tensor G using computed normals
constant_elongation_3d_3.tst:
constant_elongation_3d_3.c: constant_elongation_3d.c
	ln -s constant_elongation_3d.c constant_elongation_3d_3.c

# Project the tensor G using computed normals. Time step 20 times bigger (1.e-3)
constant_elongation_3d_4.tst:
constant_elongation_3d_4.c: constant_elongation_3d.c
	ln -s constant_elongation_3d.c constant_elongation_3d_4.c

# Project the tensor G using computed normals. Time step is 1.e-2
constant_elongation_3d_5.tst:
constant_elongation_3d_5.c: constant_elongation_3d.c
	ln -s constant_elongation_3d.c constant_elongation_3d_5.c

# tilted plane
constant_elongation_3d_6.tst:
constant_elongation_3d_6.c: constant_elongation_3d.c
	ln -s constant_elongation_3d.c constant_elongation_3d_6.c

# horizontal plane
constant_elongation_3d_axes_1.tst: CFLAGS += -DROT_X=1
constant_elongation_3d_axes_1.c: constant_elongation_3d_axes.c
	ln -s constant_elongation_3d_axes.c constant_elongation_3d_axes_1.c

# horizontal plane
constant_elongation_3d_axes_2.tst: CFLAGS += -DROT_Y=1
constant_elongation_3d_axes_2.c: constant_elongation_3d_axes.c
	ln -s constant_elongation_3d_axes.c constant_elongation_3d_axes_2.c

# horizontal plane
constant_elongation_3d_axes_3.tst: CFLAGS += -DROT_Z=1
constant_elongation_3d_axes_3.c: constant_elongation_3d_axes.c
	ln -s constant_elongation_3d_axes.c constant_elongation_3d_axes_3.c

# horizontal plane, compute Ts as well
constant_elongation_3d_axes_4.tst: CFLAGS += -DROT_X=1
constant_elongation_3d_axes_4.c: constant_elongation_3d_axes.c
	ln -s constant_elongation_3d_axes.c constant_elongation_3d_axes_4.c

# horizontal plane, compute Ts as well
constant_elongation_3d_axes_5.tst: CFLAGS += -DROT_Y=1
constant_elongation_3d_axes_5.c: constant_elongation_3d_axes.c
	ln -s constant_elongation_3d_axes.c constant_elongation_3d_axes_5.c

# horizontal plane, compute Ts as well
constant_elongation_3d_axes_6.tst: CFLAGS += -DROT_Z=1
constant_elongation_3d_axes_6.c: constant_elongation_3d_axes.c
	ln -s constant_elongation_3d_axes.c constant_elongation_3d_axes_6.c

# horizontal plane, compute Ts as well
constant_elongation_3d_axes_7.tst: CFLAGS += -DROT_Z=1
constant_elongation_3d_axes_7.c: constant_elongation_3d_axes.c
	ln -s constant_elongation_3d_axes.c constant_elongation_3d_axes_7.c

# garbage results, just testing something
constant_elongation_3d_axes_8.tst: CFLAGS += -DROT_Z=1
constant_elongation_3d_axes_8.c: constant_elongation_3d_axes.c
	ln -s constant_elongation_3d_axes.c constant_elongation_3d_axes_8.c

# Non-constant surface divergence of u, dt=5e-3
linear_elongation_3d_axes_1.tst: CFLAGS += -DROT_Z=1
linear_elongation_3d_axes_1.c: linear_elongation_3d_axes.c
	ln -s linear_elongation_3d_axes.c linear_elongation_3d_axes_1.c

# Non-constant surface divergence of u, dt=5e-4
linear_elongation_3d_axes_2.tst: CFLAGS += -DROT_Z=1
linear_elongation_3d_axes_2.c: linear_elongation_3d_axes.c
	ln -s linear_elongation_3d_axes.c linear_elongation_3d_axes_2.c

# Non-constant surface divergence of u, dt=5e-3
linear_elongation_3d_axes_3.tst: CFLAGS += -DROT_Z=1
linear_elongation_3d_axes_3.c: linear_elongation_3d_axes.c
	ln -s linear_elongation_3d_axes.c linear_elongation_3d_axes_3.c

# advect J using 4th order finite difference scheme, G is garbage
linear_elongation_3d_axes_4.tst: CFLAGS += -DROT_Z=1
linear_elongation_3d_axes_4.c: linear_elongation_3d_axes.c
	ln -s linear_elongation_3d_axes.c linear_elongation_3d_axes_4.c

# Advect J and G using bcg.
linear_elongation_3d_axes_5.tst: CFLAGS += -DROT_Z=1
linear_elongation_3d_axes_5.c: linear_elongation_3d_axes.c
	ln -s linear_elongation_3d_axes.c linear_elongation_3d_axes_5.c

# Same as linear_elongation_3d_axes_5 but with imposed face velocity (averaged from centered velocity)
linear_elongation_3d_axes_6.tst: CFLAGS += -DROT_Z=1
linear_elongation_3d_axes_6.c: linear_elongation_3d_axes.c
	ln -s linear_elongation_3d_axes.c linear_elongation_3d_axes_6.c

# Same as linear_elongation_3d_axes_6 but along different axis
linear_elongation_3d_axes_7.tst: CFLAGS += -DROT_Y=1
linear_elongation_3d_axes_7.c: linear_elongation_3d_axes.c
	ln -s linear_elongation_3d_axes.c linear_elongation_3d_axes_7.c

# Same as linear_elongation_3d_axes_6 but along different axis
linear_elongation_3d_axes_8.tst: CFLAGS += -DROT_X=1
linear_elongation_3d_axes_8.c: linear_elongation_3d_axes.c
	ln -s linear_elongation_3d_axes.c linear_elongation_3d_axes_8.c

# Same as linear_elongation_3d_axes_6 but outputs acceleration as well
linear_elongation_3d_axes_9.tst: CFLAGS += -DROT_Z=1
linear_elongation_3d_axes_9.c: linear_elongation_3d_axes.c
	ln -s linear_elongation_3d_axes.c linear_elongation_3d_axes_9.c

# Same as linear_elongation_3d_axes_6 but playing with AMR
linear_elongation_3d_axes_10.tst: CFLAGS += -DROT_Z=1
linear_elongation_3d_axes_10.c: linear_elongation_3d_axes.c
	ln -s linear_elongation_3d_axes.c linear_elongation_3d_axes_10.c

# 3D shear flow of initially spherical capsule
3D_nh_shear_mpi_1.tst:
3D_nh_shear_mpi_1.c: 3D_nh_shear_mpi.c
	ln -s 3D_nh_shear_mpi.c 3D_nh_shear_mpi_1.c

# Nb iterations for extension of normal vector is 100
3D_nh_shear_mpi_2.tst: CFLAGS += -DOUTPUT_FREQ=1 -DTEND=0.01
3D_nh_shear_mpi_2.c: 3D_nh_shear_mpi.c
	ln -s 3D_nh_shear_mpi.c 3D_nh_shear_mpi_2.c

# Nb iterations for extension of normal vector is 30
3D_nh_shear_mpi_3.tst: CFLAGS += -DOUTPUT_FREQ=1 -DTEND=0.01
3D_nh_shear_mpi_3.c: 3D_nh_shear_mpi.c
	ln -s 3D_nh_shear_mpi.c 3D_nh_shear_mpi_3.c

# Nb iterations for extension of normal vector is 30
3D_nh_shear_mpi_4.tst: CFLAGS += -DOUTPUT_FREQ=50 -DTEND=10
3D_nh_shear_mpi_4.c: 3D_nh_shear_mpi.c
	ln -s 3D_nh_shear_mpi.c 3D_nh_shear_mpi_4.c
