/**
# Set of functions for a polyhedron
*/

# include "DLMFD_foreach_region_plusplus.h"


/** Distributes points over an edge of the polyhedron */
//----------------------------------------------------------------------------
void distribute_points_edge( GeomParameter const* gcp, coord const corner1, 
	coord const corner2, RigidBodyBoundary* dlm_bd, int const lN, 
	int const istart, coord const normalvec )
//----------------------------------------------------------------------------
{
  if ( lN > 0 )
  {
    coord dinc;

    foreach_dimension()
      dinc.x = (corner2.x - corner1.x)/(lN-1);

    for (int i = 1; i <= lN-2; i++)
      foreach_dimension()
      {
        dlm_bd->bp[istart + i -1].x = corner1.x + (double)i * dinc.x;
	dlm_bd->outwardnormalvector[istart + i -1].x = normalvec.x;
      }	
  }
}



/** Determines on which side of a plane a point lies */
//----------------------------------------------------------------------------
int determ_posi_plane( coord* pointOne, coord* pointTwo,
	coord* pointThree, coord* pointCheck )
//----------------------------------------------------------------------------
{
  // Equation of the plan: ax + by + cz + k = 0
  double x1 = pointOne->x;
  double y1 = pointOne->y;
  double z1 = pointOne->z;
  double x2 = pointTwo->x;
  double y2 = pointTwo->y;
  double z2 = pointTwo->z;
  double x3 = pointThree->x;
  double y3 = pointThree->y;
  double z3 = pointThree->z;
  double xc = pointCheck->x;
  double yc = pointCheck->y;
  double zc = pointCheck->z;

  // Compute coefficients a, b, c
  double cross_a = (y2 - y1) * (z3 - z2) - (z2 - z1) * (y3 - y2);
  double cross_b = (z2 - z1) * (x3 - x2) - (x2 - x1) * (z3 - z2);
  double cross_c = (x2 - x1) * (y3 - y2) - (y2 - y1) * (x3 - x2);

  // Compute the value of k
  double k =  - (cross_a*x1 + cross_b*y1 + cross_c*z1);

  // Plugin the tested point (xc, yc, zc)
  double check_value  = cross_a*xc + cross_b*yc + cross_c*zc + k;

  // Determine the position of the test point relative to the plan
  // created by three surface points
  int retVal;
  if ( fabs( check_value ) > 1.e-13 )
    retVal = (k*check_value > 0) - (k*check_value < 0);
  else
    retVal = 0;

  return ( retVal );
}




/** Tests whether a point lies inside the polyhedron */
//----------------------------------------------------------------------------
bool is_in_Polyhedron_geomtest( double x1, double y1, double z1,
	GeomParameter const* gcp, bool const expanded )
//----------------------------------------------------------------------------
{
  // Coordinates of the checkpoint, relative to the center of mass
  coord checkpt, refcorner, cornerTwo, cornerThree;
  checkpt.x = x1 - gcp->center.x;
  checkpt.y = y1 - gcp->center.y;
  checkpt.z = z1 - gcp->center.z;

  int nfaces = gcp->pgp->nfaces;
  int iref, i1, i2, ichoice;

  ichoice = 0;
  int npoints;

  int* position = (int *) calloc(nfaces, sizeof(int));
  for (int i = 0; i < nfaces; i++)
  {
    npoints = gcp->pgp->numPointsOnFaces[i];

    iref = gcp->pgp->cornersIndex[i][ichoice];
    i1 = gcp->pgp->cornersIndex[i][ichoice + 1];
    i2 = gcp->pgp->cornersIndex[i][npoints - 1];

    // Compute the coordinate of the three points relative to the
    // center of mass
    foreach_dimension()
    {
#     if LEVELDIFF_FLAG_U
        if ( expanded )
	{
          refcorner.x = gcp->pgp->cornersCoordExp[iref].x - gcp->center.x;
          cornerTwo.x = gcp->pgp->cornersCoordExp[i1].x - gcp->center.x;
          cornerThree.x = gcp->pgp->cornersCoordExp[i2].x - gcp->center.x;	
	}
	else
#     endif
        {	
          refcorner.x = gcp->pgp->cornersCoord[iref].x - gcp->center.x;
          cornerTwo.x = gcp->pgp->cornersCoord[i1].x - gcp->center.x;
          cornerThree.x = gcp->pgp->cornersCoord[i2].x - gcp->center.x;
	}
    }

    // Judge if the point lies at the same side with origin
    // compared to the plane generated by refcorner, cornerTwo
    // and cornerThree
    position[i] = determ_posi_plane( &refcorner, &cornerTwo,
	        &cornerThree, &checkpt );
  }

  bool isin = false;
  int all_position = 0;
  for (int i = 0; i < nfaces; i++) all_position += position[i] ;

  // The test point lies inside the polyhedron only if it lies on the same side
  // as the center of mass relative to all faces of the polyhedron
  if ( all_position == nfaces ) isin = true;

  free( position );

  return ( isin );
}




/** Tests whether a point lies inside the polyhedron or any of its 
periodic clones */
//----------------------------------------------------------------------------
bool is_in_Polyhedron( double x1, double y1, double z1,
	GeomParameter const* gcp )
//----------------------------------------------------------------------------
{
  double x2, y2, z2;

  // Check if it is in the master rigid body
  bool status = is_in_Polyhedron_geomtest( x1, y1, z1, gcp, false );

  // Check if it is in any periodic clone rigid body
  if ( gcp->nperclones && !status )
    for (int i = 0; i < gcp->nperclones && !status; i++)
    {
      GeomParameter clone = *gcp;
      clone.center = gcp->perclonecenters[i];
      x2 = x1 + gcp->center.x - clone.center.x;
      y2 = y1 + gcp->center.y - clone.center.y;
      z2 = z1 + gcp->center.z - clone.center.z;
      status = is_in_Polyhedron_geomtest( x2, y2, z2, gcp, false );
    }

  return ( status );
}




/** Flag boundary layer around the polyhedron */
//----------------------------------------------------------------------------
void flag_boundarylayer_Polyhedron( scalar flag_maxlevel, 
	double const dcoef, RigidBody const* p, AABB const* ld )
//----------------------------------------------------------------------------
{
  GeomParameter const* gcp = &(p->g); 
  AABB ExpBBox;
  double delta = L0 / (double)(1 << MAXLEVEL), x2, y2, z2 ; 

  foreach_dimension()
  {
    ExpBBox.min.x = gcp->BBox.min.x - dcoef * delta;
    ExpBBox.max.x = gcp->BBox.max.x + dcoef * delta;
  } 
      
  // Loops over cells in the bounding box of the expanded polyhedron
  if ( intersect( ld, &ExpBBox ) )  
    foreach_region_plus_plus( ExpBBox.min, ExpBBox.max ) 
      if ( is_leaf(cell) )
        if ( flag_maxlevel[] == 0. )
          if ( is_in_Polyhedron_geomtest( x, y, z, gcp, true ) )
	    flag_maxlevel[] = 1.;
	
  // Loops over cells in the bounding box of its clones
  AABB cloneBBox;
  coord shift;
  for (size_t i = 0; i < gcp->nperclones; i++)
  {
    foreach_dimension() shift.x = gcp->perclonecenters[i].x - gcp->center.x; 
    assign_shifted_BBox( &cloneBBox, &ExpBBox, shift );
    if ( intersect( ld, &cloneBBox ) )
      foreach_region_plus_plus(cloneBBox.min, cloneBBox.max) 
        if ( is_leaf(cell) )
	  if ( flag_maxlevel[] == 0. ) 
          {    
            x2 = x - shift.x;
            y2 = y - shift.y;
            z2 = z - shift.z;        

            if ( is_in_Polyhedron_geomtest( x2, y2, z2, gcp, true ) )
	      flag_maxlevel[] = 1.;
          }
  }	
}



/** Finds cells lying inside the polyhedron */
//----------------------------------------------------------------------------
void create_FD_Interior_Polyhedron( RigidBody* p, vector Index, 
	vector PeriodicRefCenter, AABB const* ld )
//----------------------------------------------------------------------------
{
  GeomParameter const* gcp = &(p->g);  
  Cache* fd = &(p->Interior);
  Point ppp;

  // Loops over cells in the bounding box of the sphere
  if ( intersect( ld, &(gcp->BBox) ) )
    foreach_region_plus_plus(gcp->BBox.min, gcp->BBox.max) 
      if ( is_leaf(cell) ) 
        if ( is_in_Polyhedron_geomtest( x, y, z, gcp, false ) )
          if ( (int)Index.y[] == -1 )
          {
            foreach_dimension() PeriodicRefCenter.x[] = gcp->center.x;
	    ppp.i = point.i;
            ppp.j = point.j;
            ppp.k = point.k;			
            ppp.level = point.level;
	    cache_append( fd, ppp, 0 );
            Index.y[] = p->pnum;
          }

  double x2, y2, z2;

  // Loops over cells in the bounding box of its clones
  AABB cloneBBox;
  coord shift;
  for (size_t i = 0; i < gcp->nperclones; i++)
  {
    foreach_dimension() shift.x = gcp->perclonecenters[i].x - gcp->center.x; 
    assign_shifted_BBox( &cloneBBox, &(gcp->BBox), shift );
    if ( intersect( ld, &cloneBBox ) )
      foreach_region_plus_plus(cloneBBox.min, cloneBBox.max) 
        if ( is_leaf(cell) ) 
        {    
          x2 = x - shift.x;
          y2 = y - shift.y;
          z2 = z - shift.z;        
	  if ( is_in_Polyhedron_geomtest( x2, y2, z2, gcp, false ) )
            if ( (int)Index.y[] == -1 )
            {
              foreach_dimension() 
	        PeriodicRefCenter.x[] = gcp->perclonecenters[i].x;
	      ppp.i = point.i;
              ppp.j = point.j;
              ppp.k = point.k;			
              ppp.level = point.level;
	      cache_append( fd, ppp, 0 );
              Index.y[] = p->pnum;
            }
        }
  }

  cache_shrink( fd );
}




/** Update geometric parameters with the reference rigid body */
//----------------------------------------------------------------------------
void update_Polyhedron_from_RBRef( GeomParameter* gcp, RigidBody const* RBRef,
	const double RotMat[3][3] )
//----------------------------------------------------------------------------
{
  size_t nc = RBRef->g.pgp->ncorners;
  size_t nf = RBRef->g.pgp->nfaces; 

  // Allocate the PolyGeomParameter structure
  gcp->pgp = (PolyGeomParameter*) malloc( sizeof(PolyGeomParameter) );
  gcp->pgp->ncorners = nc;

  // Allocate the array of corner coordinates
  gcp->pgp->cornersCoord = (coord*) malloc( nc * sizeof(coord) );

  // Compute the point/corner coordinates
  for (size_t i=0;i<nc;++i)
  {
    // Rotation
    matCoordDotProduct( RotMat, RBRef->g.pgp->cornersCoord[i], 
    	&(gcp->pgp->cornersCoord[i]) );	

    // Translation
    foreach_dimension()
      gcp->pgp->cornersCoord[i].x += gcp->center.x;     
  }

# if LEVELDIFF_FLAG_U
    // Allocate the array of corner coordinates of the expanded polyhedron
    gcp->pgp->cornersCoordExp = (coord*) malloc( nc * sizeof(coord) );    

    // Compute the point/corner coordinates of the expanded polyhedron
    for (size_t i=0;i<nc;++i)
    {
      // Rotation
      matCoordDotProduct( RotMat, RBRef->g.pgp->cornersCoordExp[i], 
    	&(gcp->pgp->cornersCoordExp[i]) );	

      // Translation
      foreach_dimension()
        gcp->pgp->cornersCoordExp[i].x += gcp->center.x;     
    }        
# endif   

  // Allocate the array of number of points/corners on each face
  gcp->pgp->nfaces = nf;
  gcp->pgp->numPointsOnFaces = (long int*) malloc( nf * sizeof(long int) );

  // Allocate the array of point/corner indices on each face
  gcp->pgp->cornersIndex = (long int**) malloc( nf * sizeof(long int*) );
  
  // Assign the face indices
  long int nppf;
  for (size_t i=0;i<nf;++i)
  {
    // Number of points/corners on the face
    nppf = RBRef->g.pgp->numPointsOnFaces[i];
    gcp->pgp->numPointsOnFaces[i] = nppf;
    
    // Allocate the point/corner index vector on the face
    gcp->pgp->cornersIndex[i] = (long int*) malloc( nppf * sizeof(long int) );
    
    // Point/corner indices
    for (size_t j=0;j<nppf;++j)
      gcp->pgp->cornersIndex[i][j] = RBRef->g.pgp->cornersIndex[i][j];    
  }
}




/** Frees the geometric parameters of the polyhedron */
//----------------------------------------------------------------------------
void free_Polyhedron( GeomParameter* gcp )
//----------------------------------------------------------------------------
{
  // Free the point/corner coordinate array
  free( gcp->pgp->cornersCoord );
  gcp->pgp->cornersCoord = NULL;
  gcp->pgp->ncorners = 0;

  // Free the point/corner arrays
  long int* in = NULL;
  for (size_t i=0;i<gcp->pgp->nfaces;++i)
  {
    in = &(gcp->pgp->cornersIndex[i][0]);
    free( in );
    in = NULL;
  }
  free( gcp->pgp->cornersIndex );
  gcp->pgp->cornersIndex = NULL;
  free( gcp->pgp->numPointsOnFaces );
  gcp->pgp->numPointsOnFaces = NULL;
  gcp->pgp->nfaces = 0;

# if LEVELDIFF_FLAG_U
    // Free the point/corner coordinate array of the expanded polyhedron
    free( gcp->pgp->cornersCoordExp );
    gcp->pgp->cornersCoordExp = NULL;  
# endif  

  // Free the PolyGeomParameter structure
  free( gcp->pgp );
  gcp->pgp = NULL;  
}
