# Bits extension
GRAINS_BITS_EXT=""
if [ $GRAINS_BITS_DEFAULT = "64" ] 
then
  GRAINS_BITS_EXT=64
fi
export GRAINS_BITS_EXT
# End Bits extension

# MPI linking libs
export LIBMPI_FOR_GRAINS___=$(echo -e ${GRAINS_MPI_LIBS} | sed 's%[^ ][^ ]*%-l&%g')
# End MPI linking libs

# Xerces definition
export XERCESCROOT=/home/gitlab-runner/dependencies/XERCES-2.8.0
export XERCESC_ROOT=${XERCESCROOT}
# End Xerces definition

# Other definitions
export GRAINS_ROOT=${GRAINS_HOME}/Grains
# End other definitions

# Full extension
export GRAINS_FULL_EXT=${GRAINS_BITS_EXT}-${GRAINS_MPI_DISTRIB}-${GRAINS_MPI_VERSION}-${GRAINS_SERCOMPIL_ENV}-${GRAINS_SERCOMPIL_VERSION}
# End Full extension

# LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${GRAINS_ROOT}/lib${GRAINS_FULL_EXT}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${GRAINS_MPI_LIBDIR}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${XERCESC_ROOT}/lib${GRAINS_BITS_EXT}-${GRAINS_SERCOMPIL_ENV}-${GRAINS_SERCOMPIL_VERSION}
# End LD_LIBRARY_PATH

# Display
echo -e '\033[31m*** Grains3D shell variables\033[0m'
echo -e '\033[31mGRAINS_HOME\033[0m =' $GRAINS_HOME
echo -e '\033[31mGRAINS_ROOT\033[0m =' $GRAINS_ROOT
echo -e '\033[31mGRAINS_BITS_DEFAULT\033[0m =' $GRAINS_BITS_DEFAULT
echo -e '\033[31mGRAINS_BITS_EXT\033[0m =' $GRAINS_BITS_EXT
echo -e '\033[31mGRAINS_SERCOMPIL_ENV\033[0m =' $GRAINS_SERCOMPIL_ENV
echo -e '\033[31mGRAINS_SERCOMPIL_VERSION\033[0m =' $GRAINS_SERCOMPIL_VERSION
echo -e '\033[31mGRAINS_CPP\033[0m =' $GRAINS_CPP
echo -e '\033[31mGRAINS_C\033[0m =' $GRAINS_C
echo -e '\033[31mGRAINS_COMPIL_OPT\033[0m =' $GRAINS_COMPIL_OPT
echo -e '\033[31mGRAINS_MPI_ROOT\033[0m =' $GRAINS_MPI_ROOT
echo -e '\033[31mGRAINS_MPI_DISTRIB\033[0m =' $GRAINS_MPI_DISTRIB
echo -e '\033[31mGRAINS_MPI_VERSION\033[0m =' $GRAINS_MPI_VERSION
echo -e '\033[31mGRAINS_MPI_INCDIR\033[0m =' $GRAINS_MPI_INCDIR
echo -e '\033[31mGRAINS_MPI_BINDIR\033[0m =' $GRAINS_MPI_BINDIR
echo -e '\033[31mGRAINS_MPI_LIBDIR\033[0m =' $GRAINS_MPI_LIBDIR
echo -e '\033[31mGRAINS_MPI_LIBS\033[0m =' $GRAINS_MPI_LIBS
echo -e '\033[31mLIBMPI_FOR_GRAINS___\033[0m =' $LIBMPI_FOR_GRAINS___
echo -e '\033[31mGRAINS_MPICCC\033[0m =' $GRAINS_MPICCC
echo -e '\033[31mGRAINS_FULL_EXT\033[0m =' $GRAINS_FULL_EXT
echo -e '\033[31mXERCESCROOT & XERCESC_ROOT\033[0m =' $XERCESCROOT '&' $XERCESC_ROOT

