#!/bin/bash
# HELP
if [ $1 == "--help" ]
then

echo 'Parameters'
echo '$1 = input data file'
echo '$2 = number of procs (DEFAULT = 1)'
echo '$3 = executable mode exe0 or exe2 (DEFAULT = exe0)'

else

# RUN
# Number of procs
NB_PROCS=1
if [ $2 ]   
  then 
    NB_PROCS=$2
fi

# Exe0 or exe2
macexe="exe2"
if [ $3 ]
  then
    if [ $3 != "exe2" ]   
      then 
        macexe="exe0"
    fi
  else
    macexe="exe0"
fi

# Display header on current display
echo '--------------------------------------'
echo 'Run PACIFIC with'
echo '* Executable' $macexe 'in' $MACWORLD_BITS_DEFAULT 'bits'
echo '* Compiled with' $MACWORLD_SERCOMPIL_ENV'-'$MACWORLD_SERCOMPIL_VERSION
echo '* MPI wrapper' $MACWORLD_MPI_DISTRIB'-'$MACWORLD_MPI_VERSION
echo '* Number of procs:' $NB_PROCS
echo '* Input data file:' $1
echo '--------------------------------------'

# Delete log file
rm -f pacific.log

# Petsc options
Petsc_options_2D="-Xpetsc -options_table"
Petsc_options_3D="-Xpetsc -pc_hypre_boomeramg_strong_threshold -Xpetsc 0.25 -Xpetsc -pc_hypre_boomeramg_coarsen_type -Xpetsc PMIS -Xpetsc -pc_hypre_boomeramg_interp_type -Xpetsc ext+i -Xpetsc -pc_hypre_boomeramg_P_max -Xpetsc 4 -Xpetsc -pc_hypre_boomeramg_agg_nl -Xpetsc 1 -Xpetsc -options_table"
Petsc_options="${Petsc_options_3D}"

## Commande de run MPI pour MAC
MAC_mpi_exec_command="-Mpicom mpirun -Mpicom --hostfile -Mpicom my_hostfile"

# Run Pacific
mac run -noautocheck $Petsc_options $MAC_mpi_exec_command -np $NB_PROCS ${FLUID_MAC_HOME}/lib/Linux-${MAC_FULL_EXT}/$macexe $1 cout | tee --append pacific.log
#valgrind --tool=callgrind mac run -noautocheck $Petsc_options $MAC_mpi_exec_command -np $NB_PROCS ${FLUID_MAC_HOME}/lib/Linux-${MAC_FULL_EXT}/$macexe $1 cout | tee --append pacific.log

fi
