add_executable(Grains3DGPU_ContactForces main.cpp)

target_link_libraries(Grains3DGPU_ContactForces PRIVATE
  Grains3DGPU_obj
)

set_source_files_properties(main.cpp PROPERTIES LANGUAGE CUDA)

set_target_properties(Grains3DGPU_ContactForces PROPERTIES
  CUDA_STANDARD ${GRAINS3D_GPU_CUDA_STANDARD}
  CUDA_STANDARD_REQUIRED ${GRAINS3D_GPU_CUDA_STANDARD_REQUIRED}
  CUDA_ARCHITECTURES ${GRAINS3D_GPU_CUDA_ARCHITECTURES}
  CUDA_SEPARABLE_COMPILATION ${GRAINS3D_GPU_CUDA_SEPARABLE_COMPILATION}
  CUDA_RESOLVE_DEVICE_SYMBOLS ${GRAINS3D_GPU_CUDA_RESOLVE_DEVICE_SYMBOLS}
)

foreach(cuda_opt IN LISTS GRAINS3D_GPU_CUDA_COMPILE_OPTIONS_LIST)
  target_compile_options(Grains3DGPU_ContactForces PRIVATE
    $<$<COMPILE_LANGUAGE:CUDA>:${cuda_opt}>
  )
endforeach()

