   $DS_X = component( $DV_X, 0 )
   $DS_Y = component( $DV_X, 1 )
   $DS_Uin = 1.E0


   MODULE FV_DomainAndFields
      verbose_level = 0
      nb_space_dimensions = 2

      // Domain coordinates
      $DS_Xmin = 0.
      $DS_Xmax = 20.
      $DS_Ymin = 0.
      $DS_Ymax = 20.
      
      MODULE FV_Mesh
         $IS_NB_MESHES_X = 120
         $IS_NB_MESHES_Y = 120
	 vertices_coordinate_0 = regular_vector( $DS_Xmin, $IS_NB_MESHES_X, $DS_Xmax )
	 vertices_coordinate_1 = regular_vector( $DS_Ymin, $IS_NB_MESHES_Y, $DS_Ymax )
      END MODULE FV_Mesh 
      
      MODULE splitting_strategy
         $IS_ndomX = 2
         $IS_ndomY = 2   
         domain_decomposition = vector( $IS_ndomX, $IS_ndomY )
	 security_bandwidth = 4
      END MODULE splitting_strategy            

      MODULE macro_colors
	 inlet = < "left" >
	 outlet = < "right" >
	 lateral_walls = < "bottom" "bottom_left" "bottom_right" "top" "top_left" "top_right" >
      END MODULE macro_colors
      
      MODULE interior_fields 
         MODULE pressure
            name = "pressure"
            nb_components = 1
            discretization = "centered"
            storage_depth = 4
            MODULE DOFs_values
              value = < 0. >
            END MODULE DOFs_values
            MODULE DOFs_imposed_value
               MODULE xxx
                  color = "outlet"
                  component = 0
                  value = < 0. >
               END MODULE xxx
            END MODULE DOFs_imposed_value
         END MODULE pressure

         MODULE velocity
            name = "velocity"
            nb_components = 2
            discretization = "staggered"
            storage_depth = 5
            MODULE DOFs_values
              value = vector($DS_Uin, 0. )
            END MODULE DOFs_values
            MODULE DOFs_imposed_value
               MODULE xxx
                  color = "inlet"
                  component = 2
                  value = vector( $DS_Uin, 0. )
               END MODULE xxx
               MODULE xxy
                  color = "outlet"
                  component = 1
                  value = < 0. >
               END MODULE xxy
               MODULE xxz
                  color = "lateral_walls"
                  component = 1
                  value = < 0. >
               END MODULE xxz
            END MODULE DOFs_imposed_value
         END MODULE velocity
      END MODULE interior_fields      

      MODULE FV_ResultSaver
         writing_mode = "binary"
         MODULE pressure
            where_to_save = "at_vertices"
            entry_name = "P"
            field = "pressure"
         END MODULE pressure 

	 MODULE velocity
            where_to_save = "at_vertices"
            entry_name = "Velocity"
            field = "velocity"
         END MODULE velocity
     END MODULE FV_ResultSaver
   END MODULE FV_DomainAndFields

   MODULE FV_OneStepIteration
      concrete_name = "FV_SplitSystem"
      MODULE list_of_FV_OneStepIteration

      MODULE FV_OneStepIteration#VF
         concrete_name = "DDS_NavierStokes"
      
         Density = 2.e1
         Viscosity = 1.e0
         AdvectionScheme = "TVD"//"Centered"//"TVD"//"Upwind"
         AdvectionTimeAccuracy = 2
         Kai = 1.e0
         // Presence of particles in the domain
         Particles = true
         // Method of particle insertion (file/random)
         InsertionType = "file"
         Particle_FileName = "particles_input.csv"
         // Number of particles in the domain
         NParticles = 1
         // Local threshold for detecting node inside the solids (i.e. local_CFL/global_CFL)
         Local_threshold = 1.E-4
         // Type of level set function to be used to detect the solids in the fluid domain
         LevelSetType = "Sphere"

         // Presence of particles in the domain
         Stress_calculation = true
         // Number of points on solid surface for stress calculation
         Npoints = 200.           // Required only in 2D cases
	 ViscousStressOrder = "second"
	 PressureStressOrder = "first"

         MODULE DDS_NavierStokesSystem	    
         //**************************************************
         // Velocity unsteady matrix & solver
         //
            MODULE MAT_1DLAP_generic
               concrete_name = "LA_CRSmatrix"
               insertion_mode = true
            END MODULE MAT_1DLAP_generic
	       
            MODULE MAT_D_velocityDiffusion
               concrete_name = "PETSc_MPIAIJ"
               d_nz = 7
               o_nz = 3
            END MODULE MAT_D_velocityDiffusion

            // Presence of particles in the domain
            Particles = true
            // Number of particles in the domain
            NParticles = 1
         END MODULE DDS_NavierStokesSystem 
      END MODULE FV_OneStepIteration#VF

      END MODULE list_of_FV_OneStepIteration
   END MODULE FV_OneStepIteration

