MODULE MAC_Application

   // Application type
   concrete_name = "FV_StepByStepProgression"   
   
   MODULE FV_TimeIterator
      time_interval = 1.0E0
      time_step = 1.0E-3
   END MODULE FV_TimeIterator
   
   // Output & Backup copy
   $IS_ouput_backup_number = 100
   POST_INITIAL_CYCLE_NUMBER = 1
   
   number_graphics_output_times = $IS_ouput_backup_number 
   number_state_saving_times = $IS_ouput_backup_number

   MODULE MAC_ObjectWriter
      type = "last_two_cycles"
      files_basename = join( getcwd(), "Savings", "saving.mac" )
      output_format = "hybrid"
      force_write_at_last_time = true      
   END MODULE MAC_ObjectWriter
   
   #include ( join ( getcwd(), "InputFiles", "prob_def.mac" ) )   
      
END MODULE MAC_Application
