all: 	grid-test-scalar.tst \
	sphere-initialization-mpi.tst

include $(BASILISK)/Makefile.defs

# the default CFLAGS are set in $(BASILISK)/config
CFLAGS += -O2 -DMTRACE=3 #-events #-catch -DTRASH=1

sphere-initialization-mpi.tst: CC = mpicc -D_MPI=4
