# cmake/PacificEnv.cmake
function(pacific_generate_dev_env_script)
  # Usage:
  #   pacific_generate_dev_env_script(
  #     OUTPUT  "${CMAKE_BINARY_DIR}/pacific-env.sh"
  #     TARGETS Grains_main OtherExe ...
  #     EXTRA_PATH_DIRS "${CMAKE_BINARY_DIR}/some/dir" ...
  #     EXTRA_LIB_DIRS  "${CMAKE_BINARY_DIR}/some/lib" ...
  #   )

  set(options)
  set(oneValueArgs OUTPUT)
  set(multiValueArgs TARGETS EXTRA_PATH_DIRS EXTRA_LIB_DIRS)
  cmake_parse_arguments(PENV "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  if (NOT PENV_OUTPUT)
    message(FATAL_ERROR "pacific_generate_dev_env_script: OUTPUT is required")
  endif()

  # Build PATH entries from targets (generator expressions allowed here)
  set(_path_entries "")
  foreach(t IN LISTS PENV_TARGETS)
    if (NOT TARGET "${t}")
      message(FATAL_ERROR "pacific_generate_dev_env_script: TARGET '${t}' does not exist")
    endif()
    list(APPEND _path_entries "$<TARGET_FILE_DIR:${t}>")
  endforeach()
  foreach(d IN LISTS PENV_EXTRA_PATH_DIRS)
    list(APPEND _path_entries "${d}")
  endforeach()

  # Build library path entries (optional; usually not needed if build-tree RPATH works)
  set(_lib_entries "")
  foreach(d IN LISTS PENV_EXTRA_LIB_DIRS)
    list(APPEND _lib_entries "${d}")
  endforeach()

  # Join lists into colon-separated strings for sh
  list(JOIN _path_entries ":" _PATH_JOINED)
  list(JOIN _lib_entries  ":" _LIB_JOINED)

  # Generate the actual script
  # NOTE: file(GENERATE) evaluates generator expressions like $<TARGET_FILE_DIR:...>
  file(GENERATE
    OUTPUT "${PENV_OUTPUT}"
    CONTENT
"#!/usr/bin/env bash
# Source this file (do not execute):  source \"${PENV_OUTPUT}\"

# This script is generated by CMake. It modifies your current shell environment.

# Add PacIFiC build-tree executables to PATH
export PATH=\"${_PATH_JOINED}:\$PATH\"

# Optional: only needed if you have dlopen/plugins or non-RPATH shared libs.
# Linux:
${_maybe_linux_loader}
# macOS:
${_maybe_macos_loader}

echo \"[PacIFiC] PATH enabled for this shell.\"
"
  )

  # If you want optional loader vars emitted only when libs are provided:
  # We can patch the content with a small trick: generate those lines conditionally.
  # Simpler: always emit them guarded in shell.
  if (_LIB_JOINED)
    file(GENERATE
      OUTPUT "${PENV_OUTPUT}"
      CONTENT
"#!/usr/bin/env bash
# Source this file (do not execute):  source \"${PENV_OUTPUT}\"

export PATH=\"${_PATH_JOINED}:\$PATH\"

# Optional loader paths (mainly for dlopen/plugins or non-RPATH scenarios)
if [[ \"$(uname)\" == \"Linux\" ]]; then
  export LD_LIBRARY_PATH=\"${_LIB_JOINED}:\${LD_LIBRARY_PATH:-}\"
elif [[ \"$(uname)\" == \"Darwin\" ]]; then
  export DYLD_LIBRARY_PATH=\"${_LIB_JOINED}:\${DYLD_LIBRARY_PATH:-}\"
fi

echo \"[PacIFiC] PATH (and optional loader path) enabled for this shell.\"
"
    )
  endif()

  # # Make it executable for convenience (sourcing works either way)
  # add_custom_target(pacific-dev-env ALL
  #   COMMAND "${CMAKE_COMMAND}" -E chmod +x "${PENV_OUTPUT}"
  #   BYPRODUCTS "${PENV_OUTPUT}"
  #   COMMENT "Making pacific-env.sh executable"
  #   VERBATIM
  # )
endfunction()