#
# Subdirectories
#

add_subdirectory(Dtd)
add_subdirectory(Tools)

#
#
#

# ---- Generate Version.hh ----
configure_file(
  "${CMAKE_CURRENT_SOURCE_DIR}/Utility/include/Version.hh.in"
  "${CMAKE_CURRENT_BINARY_DIR}/Utility/include/Version.hh"
  @ONLY
)


#
# Collect Grains3D sources
#

set(GRAINS3D_INCLUDE_DIRS "")
set(GRAINS3D_SOURCES "")

# Base
list(APPEND GRAINS3D_INCLUDE_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/Base/include>")
file(GLOB GRAINS3D_BASE_SOURCES CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/Base/src/*.cpp"
)
list(SORT GRAINS3D_BASE_SOURCES)
list(APPEND GRAINS3D_SOURCES
  ${GRAINS3D_BASE_SOURCES}
)

# Component
list(APPEND GRAINS3D_INCLUDE_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/Component/include>")
file(GLOB GRAINS3D_COMPONENT_SOURCES CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/Component/src/*.cpp"
)
list(SORT GRAINS3D_COMPONENT_SOURCES)
list(APPEND GRAINS3D_SOURCES
  ${GRAINS3D_COMPONENT_SOURCES}
)

# Fluid
list(APPEND GRAINS3D_INCLUDE_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/Fluid/include>")
file(GLOB GRAINS3D_FLUID_SOURCES CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/Fluid/src/*.cpp"
)
list(SORT GRAINS3D_FLUID_SOURCES)
list(APPEND GRAINS3D_SOURCES
  ${GRAINS3D_FLUID_SOURCES}
)

# Geometry
list(APPEND GRAINS3D_INCLUDE_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/Geometry/include>")
file(GLOB GRAINS3D_GEOMETRY_SOURCES CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/Geometry/src/*.cpp"
)
list(SORT GRAINS3D_GEOMETRY_SOURCES)
list(APPEND GRAINS3D_SOURCES
  ${GRAINS3D_GEOMETRY_SOURCES}
)

# InterfaceCBasilisk
list(APPEND GRAINS3D_INCLUDE_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/InterfaceCBasilisk/include>")
file(GLOB GRAINS3D_INTERFACECBASILISK_SOURCES CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/InterfaceCBasilisk/src/*.cpp"
)
list(SORT GRAINS3D_INTERFACECBASILISK_SOURCES)
list(APPEND GRAINS3D_SOURCES
  ${GRAINS3D_INTERFACECBASILISK_SOURCES}
)

# PostProcessing
list(APPEND GRAINS3D_INCLUDE_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/PostProcessing/include>")
file(GLOB GRAINS3D_POSTPROCESSING_SOURCES CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/PostProcessing/src/*.cpp"
)
list(SORT GRAINS3D_POSTPROCESSING_SOURCES)
list(APPEND GRAINS3D_SOURCES
  ${GRAINS3D_POSTPROCESSING_SOURCES}
)

# TimeIntegration
list(APPEND GRAINS3D_INCLUDE_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/TimeIntegration/include>")
file(GLOB GRAINS3D_TIMEINTEGRATION_SOURCES CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/TimeIntegration/src/*.cpp"
)
list(SORT GRAINS3D_TIMEINTEGRATION_SOURCES)
list(APPEND GRAINS3D_SOURCES
  ${GRAINS3D_TIMEINTEGRATION_SOURCES}
)

# Utility
list(APPEND GRAINS3D_INCLUDE_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/Utility/include>")
file(GLOB GRAINS3D_UTILITY_SOURCES CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/Utility/src/*.cpp"
)
list(SORT GRAINS3D_UTILITY_SOURCES)
list(APPEND GRAINS3D_SOURCES
  ${GRAINS3D_UTILITY_SOURCES}
)

# XML3
list(APPEND GRAINS3D_INCLUDE_DIRS "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/XML3/include>")
file(GLOB GRAINS3D_XML3_SOURCES CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/XML3/src/*.cpp"
)
list(SORT GRAINS3D_XML3_SOURCES)
list(APPEND GRAINS3D_SOURCES
  ${GRAINS3D_XML3_SOURCES}
)



#
# Build Grains3D shared object
#

# message(STATUS ">>> GRAINS3D_SOURCES = ${GRAINS3D_SOURCES}")

set(CMAKE_CXX_VISIBILITY_PRESET default)
set(CMAKE_VISIBILITY_INLINES_HIDDEN  OFF)

add_library(Grains3D SHARED ${GRAINS3D_SOURCES})
add_library(PacIFiC::Grains3D ALIAS Grains3D) 

set_target_properties(Grains3D PROPERTIES
  OUTPUT_NAME "Grains3D"
)

set_target_properties(Grains3D PROPERTIES
  VERSION ${PROJECT_VERSION}
  SOVERSION ${PROJECT_VERSION_MAJOR}
)

set_target_properties(Grains3D PROPERTIES
  CXX_VISIBILITY_PRESET default
)
 
target_include_directories(Grains3D
  PUBLIC
    ${GRAINS3D_INCLUDE_DIRS}
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
)

if (PACIFIC_ENABLE_MPI)
  target_link_libraries(Grains3D 
    PUBLIC
      MPI::MPI_C
      ZLIB::ZLIB
      XercesC::XercesC
  )
else()
  target_link_libraries(Grains3D 
    PUBLIC
      ZLIB::ZLIB
      XercesC::XercesC
  )
endif()
 
